version: '2'

services:
  bitcore:
    container_name: bitcore
    build: .
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - NETWORK=livenet
    ports:
      - 80:3001
      - 8333
    volumes:
      - bitcore_data:/src/data
      - node_modules:/usr/local/lib/node_modules
  trezor-wallet:
    container_name: trezor-wallet
    image: jonathascarrijo/docker-trezor-wallet
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  bitcore_data:
    external: true
  node_modules:
